### Datavidenskab i Numpy, Pandas og Matplotlib ###

- Hvad er biblioterkerne/libraries Numpy, Pandas og Matplotlib?

- Hvordan bruger man Numpy og Matplotlib?

### Libraries Definition  ###

#### Numpy - Math operations and arrays ####
(Lineær Algebra), LaPack (Lineær Algebra), Numerical data, simulation Blas

Pros:
- Multidimentional array for 1d, 2d and 3d arrays.
- Matrix (2d array)
- Matematiske operationer
- Best for handling big datasets
- Linear Algebra and statistics
- Numpy is fast, as it uses less bytes of memory
- No type checking when iteraing through objects (string, float, ...)
- Contiguos memory - Memory scattered together in one place
- SIMD Vector processiong
- Effective Cache Utilization

Different from List:
- More flexible in computation 

Applications:
- Matlab replacement
- Plotting (Matplotlib)
- Backend( Pandas, Connect 4, Digital Photography)
- Store pgn images
- Machine Learning
- 


F.eks:
Computer binær sprog:

5 = 00000101 => numpy int32 

### Pandas - Data manipulation ###
Library used for handling structured data like tables (CSV, Excel, databases) Panel Data, Tabular data, data analyse, methods for loading, reshaping, pivoting, joining, missing data. C, Cyphon.

Pros:
- Best for table handling, filtering and transforming data
- Panel Data, 
- Tabular data, 
- Data analyses, 
- Methods for loading, reshaping, pivoting, joining, missing data. 
- Used with C, Cyphon.

### Matplotlib - Data visualisation ###
Used for creating charts and graphs for better data understanding

Pros:
- Best for data visualization 
- Best for creating plots, graphs and charts
- Best for visualising trends and patterns

In [6]:
#Introduction to Numpy

import numpy as np

In [8]:
#Basics:

a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [9]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [10]:
a.ndim

1

In [11]:
b.shape

(2, 3)

In [13]:
a.dtype

dtype('int64')

In [15]:
a.itemsize

8

In [17]:
# Get total size
a.nbytes

24